spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none

  jackson:
    default-property-inclusion: NON_NULL

  kafka:
    consumer:
      bootstrap-servers:
      group-id: notification.send_sms_consumer_group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer